version: "3.7"

# 申明同一个网络
networks:
  net:
    name: net

# 游戏数据卷
volumes:
  consuldata:
    name: consuldata
  redisdata:
    name: redisdata
  mongodata:
    name: mongodata
  nginxdata:
    name: nginxdata

# 服务
services:
  redis:
    image: redis:latest
    ports:
    - "6379:6379"
    networks:
      net:
        # 给网络取别名,可以用redis和cache找到
        aliases:
          - cache
    command: /etc/redis/redis.conf
    volumes:
      # 持久存储redis的数据
      - redisdata:/data
      # 挂载本地配置文件
      - ./redis.conf:/etc/redis/redis.conf
      # 时间同步
      # - /etc/localtime:/etc/localtime
  mongo:
    image: mongo:latest
    ports:
    - "27017:27017"
    networks:
      net:
        # 给网络取别名,可以用mongodb和db找到
        aliases:
          - db
    command: ["mongod", "-f", "/etc/mongo/mongod.conf"]
    volumes:
      # 持久存储mongodb的数据
      - mongodata:/data/db:rw
      - mongodata:/data/configdb:rw
      # 挂载本地配置文件
      - ./mongod.conf:/etc/mongo/mongod.conf:rw

  consul:
    image: consul:latest
    ports:
    - "8500:8500"
    command: consul agent -server -bootstrap -data-dir /consul/data -node=ylconsul -bind=0.0.0.0 -config-dir=/consul/config/ -client=0.0.0.0 -ui
    networks:
      net:
        # 给网络取别名,可以用consul和discovery找到
        aliases:
          - discovery
    volumes:
      - consuldata:/consul/data
      
  nats:
    image: nats:latest
    ports:
    - "4222:4222"
    - "6222:6222"
    - "8222:8222"
    command: "-c /etc/nats/nats.conf"
    networks:
      net:
        aliases:
          - nats
    volumes:
      - ./nats.conf:/etc/nats/nats.conf:rw

  # demo1:
  #   image: golang:alpine
  #   networks:
  #     net:
  #       aliases:
  #         - work
  #   volumes:
  #     - ../:/usr/local/work
  #   depends_on:
  #     - nats
  #     - consul
  #     - redis
  #     - mongo
  #   working_dir: /usr/local/work
  #   entrypoint: ["./demo1", "-sID", "demo1"]
  #   # 模拟一个伪终端
  #   tty: true


  # proxy:
  #   image: nginx:latest
  #   restart: always
  #   volumes:
  #     - ./nginx/conf.d/:/etc/nginx/conf.d/
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/log/:/var/log/nginx/:rw
  #     - nginxdata/:/var/cache/nginx
  #     - nginxdata/:/run
  #   networks:
  #     - net
  #   ports:
  #     - 9000-10000:9000-10000
  #     - 80:80
  #     - 443:443
  #   depends_on:
  #     - nats
  #     - consul
  #     - redis
  #     - demo1