Id = "gate_1"                        #服务的唯一id 不可重复
Tag = "demo"                        #服务集群标签 相同标签 sys.registry 和 sys.rpc 配置一致 即可互相发现和通信
Type = "gate"                      #服务类型 相同服务类型相同 如 多个login 服务 相同服务多开 服务类型一致
Category = "BusinessService"        #服务类别 例如 网关服务器 或者 游戏服务器 以及普通业务服务器
Version = 1                         #服务版本 多服务器相同的服务类型 高版本比低版本拥有更高的访问优先级 使用场景 热更新机制

[Settings]

# 日志系统  基础系统 每个服务默认启动
[Sys.log]
FileName = "./log/gate_1.log"
Loglayer = 2
Loglevel = 0
Debugmode = true
# 注册表系统 集群服务基础系统 集群服务默认启动
[Sys.registry]
ConsulAddr = "127.0.0.1:8500"
# rpc通信系统 集群服务基础系统 集群服务默认启动
[Sys.rpc]
NatsAddr = "nats://127.0.0.1:4222"

[Modules.SM_ClubModule]
