// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: db_article.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//作者
type DB_AuthorData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthoIrd    uint32   `protobuf:"varint,1,opt,name=AuthoIrd,proto3" json:"AuthoIrd,omitempty" bson:"_id"` //tags:{bson:"_id"}作者id
	PhonOrEmail string   `protobuf:"bytes,2,opt,name=PhonOrEmail,proto3" json:"PhonOrEmail,omitempty"`
	Password    string   `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	NickName    string   `protobuf:"bytes,4,opt,name=NickName,proto3" json:"NickName,omitempty"`
	HeadUrl     string   `protobuf:"bytes,5,opt,name=HeadUrl,proto3" json:"HeadUrl,omitempty"`
	ArticleIds  []uint32 `protobuf:"varint,6,rep,packed,name=ArticleIds,proto3" json:"ArticleIds,omitempty"` //文章列表
}

func (x *DB_AuthorData) Reset() {
	*x = DB_AuthorData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_article_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DB_AuthorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DB_AuthorData) ProtoMessage() {}

func (x *DB_AuthorData) ProtoReflect() protoreflect.Message {
	mi := &file_db_article_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DB_AuthorData.ProtoReflect.Descriptor instead.
func (*DB_AuthorData) Descriptor() ([]byte, []int) {
	return file_db_article_proto_rawDescGZIP(), []int{0}
}

func (x *DB_AuthorData) GetAuthoIrd() uint32 {
	if x != nil {
		return x.AuthoIrd
	}
	return 0
}

func (x *DB_AuthorData) GetPhonOrEmail() string {
	if x != nil {
		return x.PhonOrEmail
	}
	return ""
}

func (x *DB_AuthorData) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DB_AuthorData) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *DB_AuthorData) GetHeadUrl() string {
	if x != nil {
		return x.HeadUrl
	}
	return ""
}

func (x *DB_AuthorData) GetArticleIds() []uint32 {
	if x != nil {
		return x.ArticleIds
	}
	return nil
}

type DB_ArticleData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint32   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" bson:"_id"`                     //tags:{bson:"_id"}文章id
	Title        string   `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`                //文章标题
	ShortContent string   `protobuf:"bytes,3,opt,name=ShortContent,proto3" json:"ShortContent,omitempty"`  //短内容
	Content      string   `protobuf:"bytes,4,opt,name=Content,proto3" json:"Content,omitempty"`            //文章内容
	Images       []string `protobuf:"bytes,5,rep,name=Images,proto3" json:"Images,omitempty"`              //文章图片
	CreationTime int64    `protobuf:"varint,6,opt,name=CreationTime,proto3" json:"CreationTime,omitempty"` //传作时间
	AuthorId     uint32   `protobuf:"varint,7,opt,name=AuthorId,proto3" json:"AuthorId,omitempty"`         //作者id
	AuthorName   string   `protobuf:"bytes,8,opt,name=AuthorName,proto3" json:"AuthorName,omitempty"`      //作者id
	AuthorAvatar string   `protobuf:"bytes,9,opt,name=AuthorAvatar,proto3" json:"AuthorAvatar,omitempty"`  //作者头像
	GreatNum     uint32   `protobuf:"varint,10,opt,name=GreatNum,proto3" json:"GreatNum,omitempty"`        //点赞数
	Messagenum   uint32   `protobuf:"varint,11,opt,name=Messagenum,proto3" json:"Messagenum,omitempty"`    //消息数
}

func (x *DB_ArticleData) Reset() {
	*x = DB_ArticleData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_article_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DB_ArticleData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DB_ArticleData) ProtoMessage() {}

func (x *DB_ArticleData) ProtoReflect() protoreflect.Message {
	mi := &file_db_article_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DB_ArticleData.ProtoReflect.Descriptor instead.
func (*DB_ArticleData) Descriptor() ([]byte, []int) {
	return file_db_article_proto_rawDescGZIP(), []int{1}
}

func (x *DB_ArticleData) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DB_ArticleData) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DB_ArticleData) GetShortContent() string {
	if x != nil {
		return x.ShortContent
	}
	return ""
}

func (x *DB_ArticleData) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DB_ArticleData) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *DB_ArticleData) GetCreationTime() int64 {
	if x != nil {
		return x.CreationTime
	}
	return 0
}

func (x *DB_ArticleData) GetAuthorId() uint32 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *DB_ArticleData) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *DB_ArticleData) GetAuthorAvatar() string {
	if x != nil {
		return x.AuthorAvatar
	}
	return ""
}

func (x *DB_ArticleData) GetGreatNum() uint32 {
	if x != nil {
		return x.GreatNum
	}
	return 0
}

func (x *DB_ArticleData) GetMessagenum() uint32 {
	if x != nil {
		return x.Messagenum
	}
	return 0
}

var File_db_article_proto protoreflect.FileDescriptor

var file_db_article_proto_rawDesc = []byte{
	0x0a, 0x10, 0x64, 0x62, 0x5f, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xbf, 0x01, 0x0a, 0x0d, 0x44, 0x42, 0x5f, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x49, 0x72, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x49, 0x72, 0x64,
	0x12, 0x20, 0x0a, 0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x4f, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x4f, 0x72, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x48, 0x65,
	0x61, 0x64, 0x55, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x48, 0x65, 0x61,
	0x64, 0x55, 0x72, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x49,
	0x64, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0a, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x49, 0x64, 0x73, 0x22, 0xcc, 0x02, 0x0a, 0x0e, 0x44, 0x42, 0x5f, 0x41, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x22, 0x0a,
	0x0c, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x41, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x47, 0x72, 0x65, 0x61, 0x74,
	0x4e, 0x75, 0x6d, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x47, 0x72, 0x65, 0x61, 0x74,
	0x4e, 0x75, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x6e, 0x75,
	0x6d, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x6e, 0x75, 0x6d, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_db_article_proto_rawDescOnce sync.Once
	file_db_article_proto_rawDescData = file_db_article_proto_rawDesc
)

func file_db_article_proto_rawDescGZIP() []byte {
	file_db_article_proto_rawDescOnce.Do(func() {
		file_db_article_proto_rawDescData = protoimpl.X.CompressGZIP(file_db_article_proto_rawDescData)
	})
	return file_db_article_proto_rawDescData
}

var file_db_article_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_db_article_proto_goTypes = []interface{}{
	(*DB_AuthorData)(nil),  // 0: DB_AuthorData
	(*DB_ArticleData)(nil), // 1: DB_ArticleData
}
var file_db_article_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_db_article_proto_init() }
func file_db_article_proto_init() {
	if File_db_article_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_db_article_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DB_AuthorData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_article_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DB_ArticleData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_db_article_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_db_article_proto_goTypes,
		DependencyIndexes: file_db_article_proto_depIdxs,
		MessageInfos:      file_db_article_proto_msgTypes,
	}.Build()
	File_db_article_proto = out.File
	file_db_article_proto_rawDesc = nil
	file_db_article_proto_goTypes = nil
	file_db_article_proto_depIdxs = nil
}
